# Generated by Django 2.1.1 on 2018-09-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0003_auto_20180926_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='post_time',
        ),
        migrations.AddField(
            model_name='article',
            name='post_date',
            field=models.DateField(auto_now=True),
        ),
    ]
