# Generated by Django 2.1.1 on 2018-09-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0004_auto_20180926_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_date',
            field=models.DateField(null=True),
        ),
    ]
